spring:
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://127.0.0.1:3307/tomato_giti
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: tomato
    password: tomato

  jpa:
    database: mysql
#    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

debug: true